# -*- coding: utf-8 -*-
# Developed by RAREBIRD.
{
    'name': 'Interio',
    'category': 'Theme/Creative',
    'version': '18.0.1.0.0',
    'sequence': 1,
    'author': 'RAREBIRD',
    'summary': 'Interior design theme featuring different Home pages Luxe, Crafted, Atelier, Vista with 50 unique snippets',
    'description': """
        interior design theme for Odoo.
        Our theme includes different unique Home pages Luxe, Crafted, Atelier, Vista with 50 unique snippets.
        Perfect for architects, home decor, furniture stores,
        luxury living spaces, design studios.

        Support:
        -
        For any questions or support, please contact.
    """,
    'license': 'OPL-1',
    'live_test_url': 'https://interio.xappco.site/',
    'support': 'rarebirdev@gmail.com',
    'price': 109.00,
    'currency': 'USD',

    'depends': [
        'website',
        'web_editor',
    ],

    'data': [
        "views/st_header.xml",
        "views/ambient/interio_hero1.xml",
        "views/luxe/interio_hero2.xml",
        "views/vista/interio_hero3.xml",
        "views/crafted/interio_hero4.xml",
        "views/crafted/crafted_designers.xml",
        "views/crafted/crafted_about.xml",
        "views/crafted/crafted_reviews.xml",
        "views/crafted/crafted_pure.xml",
        "views/crafted/crafted_projects.xml",
        "views/crafted/work_marquee.xml",
        "views/crafted/our_client.xml",
        "views/crafted/crafted_contact.xml",
        "views/atelier/interio_hero5.xml",
        "views/atelier/atelier_philosophy.xml",
        "views/atelier/atelier_key.xml",
        "views/atelier/atelier_pricing.xml",
        "views/atelier/atelier_follow_us.xml",
        "views/atelier/atelier_project.xml",
        "views/atelier/atelier_marquee.xml",
        "views/atelier/atelier_get_in_touch.xml",
        "views/atelier/atelier_designers.xml",
        "views/ambient/interio_project1.xml",
        "views/luxe/interio_project2.xml",
        "views/luxe/creation.xml",
        "views/luxe/interio_process.xml",
        "views/luxe/luxe_team.xml",
        "views/luxe/luxe_services.xml",
        "views/luxe/luxe_clients.xml",
        "views/luxe/luxe_marquee.xml",
        "views/luxe/luxe_contact.xml",
        "views/vista/interio_about3.xml",
        "views/vista/rooms3.xml",
        "views/vista/gallery.xml",
        "views/vista/reviews.xml",
        "views/vista/fandq.xml",
        "views/vista/members.xml",
        "views/vista/vista_marquee.xml",
        "views/vista/vista_contact.xml",
        "views/interio_footer.xml",
        "views/interio_snippets.xml",
        "views/ambient/interio_philosophy.xml",
        "views/ambient/interio_designers.xml",
        "views/ambient/ambient_contact.xml",
        "views/ambient/studio_marquee.xml",
        "views/ambient/ambient_marquee.xml",
        "views/ambient/ambient_atelier.xml",
        "views/ambient/ambient_faq.xml",
        "views/extra/extra_about.xml",
        "views/extra/extra_projects1.xml",
        "views/extra/extra_marquee1.xml",
        "views/extra/extra_visit.xml",
        "views/extra/extra_project2.xml"
    ],



    'assets': {
        'web.assets_frontend': [
            # CSS Files
            'theme_interio/static/src/css/header.css',
            'theme_interio/static/src/css/footer.css',
            'theme_interio/static/src/css/ambient/interio_hero1.css',
            'theme_interio/static/src/css/luxe/interio_hero2.css',
            'theme_interio/static/src/css/vista/interio_hero3.css',
            'theme_interio/static/src/css/crafted/interio_hero4.css',
            'theme_interio/static/src/css/crafted/crafted_designers.css',
            'theme_interio/static/src/css/crafted/crafted_about.css',
            'theme_interio/static/src/css/crafted/crafted_reviews.css',
            'theme_interio/static/src/css/crafted/crafted_pure.css',
            'theme_interio/static/src/css/crafted/crafted_projects.css',
            'theme_interio/static/src/css/crafted/work_marquee.css',
            'theme_interio/static/src/css/crafted/our_client.css',
            'theme_interio/static/src/css/crafted/crafted_contact.css',
            'theme_interio/static/src/css/atelier/interio_hero5.css',
            'theme_interio/static/src/css/atelier/atelier_philosophy.css',
            'theme_interio/static/src/css/atelier/atelier_key.css',
            'theme_interio/static/src/css/atelier/atelier_pricing.css',
            'theme_interio/static/src/css/atelier/atelier_follow_us.css',
            'theme_interio/static/src/css/atelier/atelier_project.css',
            'theme_interio/static/src/css/atelier/atelier_marquee.css',
            'theme_interio/static/src/css/atelier/atelier_get_in_touch.css',
            'theme_interio/static/src/css/atelier/atelier_designers.css',
            'theme_interio/static/src/css/ambient/interio_project1.css',
            'theme_interio/static/src/css/ambient/interio_philosophy.css',
            'theme_interio/static/src/css/ambient/interio_designers.css',
            'theme_interio/static/src/css/ambient/ambient_contact.css',
            'theme_interio/static/src/css/ambient/studio_marquee.css',
            'theme_interio/static/src/css/ambient/ambient_marquee.css',
            'theme_interio/static/src/css/ambient/ambient_atelier.css',
            'theme_interio/static/src/css/ambient/ambient_faq.css',
            'theme_interio/static/src/css/luxe/interio_project2.css',
            'theme_interio/static/src/css/luxe/creation.css',
            'theme_interio/static/src/css/luxe/interio_process.css',
            'theme_interio/static/src/css/luxe/luxe_team.css',
            'theme_interio/static/src/css/luxe/luxe_services.css',
            'theme_interio/static/src/css/luxe/luxe_clients.css',
            'theme_interio/static/src/css/luxe/luxe_marquee.css',
            'theme_interio/static/src/css/luxe/luxe_contact.css',
            'theme_interio/static/src/css/vista/interio_about3.css',
            'theme_interio/static/src/css/vista/rooms3.css',
            'theme_interio/static/src/css/vista/gallery.css',
            'theme_interio/static/src/css/vista/reviews.css',
            'theme_interio/static/src/css/vista/fandq.css',
            'theme_interio/static/src/css/vista/members.css',
            'theme_interio/static/src/css/vista/vista_marquee.css',
            'theme_interio/static/src/css/vista/vista_contact.css',
            'theme_interio/static/src/css/extra/extra_about.css',
            'theme_interio/static/src/css/extra/extra_projects1.css',
            'theme_interio/static/src/css/extra/extra_marquee1.css',
            'theme_interio/static/src/css/extra/extra_visit.css',
            'theme_interio/static/src/css/extra/extra_project2.css',



            # JavaScript Files
            'theme_interio/static/src/js/header.js',
            'theme_interio/static/src/js/footer.js',
            'theme_interio/static/src/js/ambient/interio_hero1.js',
            'theme_interio/static/src/js/luxe/interio_hero2.js',
            'theme_interio/static/src/js/vista/interio_hero3.js',
            'theme_interio/static/src/js/crafted/interio_hero4.js',
            'theme_interio/static/src/js/crafted/crafted_designers.js',
            'theme_interio/static/src/js/crafted/crafted_about.js',
            'theme_interio/static/src/js/crafted/crafted_reviews.js',
            'theme_interio/static/src/js/crafted/crafted_pure.js',
            'theme_interio/static/src/js/crafted/crafted_projects.js',
            'theme_interio/static/src/js/crafted/work_marquee.js',
            'theme_interio/static/src/js/crafted/crafted_contact.js',
            'theme_interio/static/src/js/atelier/interio_hero5.js',
            'theme_interio/static/src/js/atelier/atelier_philosophy.js',
            'theme_interio/static/src/js/atelier/atelier_pricing.js',
            'theme_interio/static/src/js/atelier/atelier_follow_us.js',
            'theme_interio/static/src/js/atelier/atelier_project.js',
            'theme_interio/static/src/js/atelier/atelier_get_in_touch.js',
            'theme_interio/static/src/js/atelier/atelier_designers.js',
            'theme_interio/static/src/js/ambient/interio_project1.js',
            'theme_interio/static/src/js/ambient/interio_designers.js',
            'theme_interio/static/src/js/ambient/ambient_contact.js',
            'theme_interio/static/src/js/ambient/studio_marquee.js',
            'theme_interio/static/src/js/ambient/ambient_atelier.js',
            'theme_interio/static/src/js/ambient/ambient_faq.js',
            'theme_interio/static/src/js/luxe/interio_project2.js',
            'theme_interio/static/src/js/luxe/creation.js',
            'theme_interio/static/src/js/luxe/interio_process.js',
            'theme_interio/static/src/js/luxe/luxe_team.js',
            'theme_interio/static/src/js/luxe/luxe_services.js',
            'theme_interio/static/src/js/luxe/luxe_clients.js',
            'theme_interio/static/src/js/vista/interio_about3.js',
            'theme_interio/static/src/js/vista/rooms3.js',
            'theme_interio/static/src/js/vista/gallery.js',
            'theme_interio/static/src/js/vista/reviews.js',
            'theme_interio/static/src/js/vista/fandq.js',
            'theme_interio/static/src/js/vista/members.js',
        ],
    },

'images': [
        'static/description/interio_cover.jpg',
        'static/description/interio_screenshot.gif',

    ],


    'installable': True,
    'auto_install': False,
    'application': False,

}
